### ISSUE TITLE
Telegram input

### ISSUE THREAD

**Issue by miztizm** [ecornell/ai-tools-ahk#4]
I tried using Telegram input, but I encountered an error when attempting to replace the text. 

![image](https://github.com/ecornell/ai-tools-ahk/assets/617020/c94ae2a7-70ab-440d-a991-579818d8f735)

![image](https://github.com/ecornell/ai-tools-ahk/assets/617020/94a73ee2-0e25-4dc9-8c9c-ed50d2993b21)

**Comment by warshell** [comment]
Ok i only found this way:

```

}else {
    ; Check if the active window is Telegram.exe with the specified class and PID
    IfWinActive, ahk_class Qt51510QWindowIcon ahk_exe Telegram.exe ahk_pid 16512
    {
        ; Perform actions specific to Telegram.exe
        Send ^v ; Paste text in Telegram
    }
    else
    {
        ; Activate the active window and paste text
        WinActivate
        A_Clipboard := text
        Send ^v
    }
}
```
